// <auto-generated />
namespace CIS526_FinalAssignment.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class path2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(path2));
        
        string IMigrationMetadata.Id
        {
            get { return "201305080503225_path2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
