// <auto-generated />
namespace CIS526_FinalAssignment.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig));
        
        string IMigrationMetadata.Id
        {
            get { return "201305100555213_mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
