// <auto-generated />
namespace CIS526_FinalAssignment.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class path : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(path));
        
        string IMigrationMetadata.Id
        {
            get { return "201305080447057_path"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
